Databases:
  DATASET: /scratch2/sdas/DATA/{uri}.wav
  BBT2: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/{uri}.wav
Protocols:
  DATASET:
    SpeakerDiarization:
      cougar:
        train:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/cougar.train.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/cougar.train.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/cougar.train.all.lst
        development:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/cougar.dev.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/cougar.dev.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/cougar.dev.all.lst
      fausey-trio:
        train:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/fausey-trio.train.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/fausey-trio.train.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/fausey-trio.train.all.lst
        development:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/fausey-trio.dev.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/fausey-trio.dev.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/fausey-trio.dev.all.lst
      lyon:
        train:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/lyon.train.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/lyon.train.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/lyon.train.all.lst
        development:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/lyon.dev.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/lyon.dev.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/lyon.dev.all.lst
      png2019:
        train:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/png2019.train.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/png2019.train.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/png2019.train.all.lst
        development:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/png2019.dev.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/png2019.dev.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/png2019.dev.all.lst
      tsimane2017:
        train:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/tsimane2017.train.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/tsimane2017.train.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/tsimane2017.train.all.lst
        development:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/tsimane2017.dev.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/tsimane2017.dev.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/tsimane2017.dev.all.lst
      vanuatu:
        train:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/vanuatu.train.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/vanuatu.train.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/vanuatu.train.all.lst
        development:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/vanuatu.dev.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/vanuatu.dev.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_2-0/vanuatu.dev.all.lst
      providence:
        train:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/providence.train.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/providence.train.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/providence.train.all.lst
        development:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/providence.dev.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/providence.dev.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/providence.dev.all.lst
      tsay:
        train:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/tsay.train.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/tsay.train.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/tsay.train.all.lst
        development:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/tsay.dev.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/tsay.dev.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/tsay.dev.all.lst
      soderstrom:
        train:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/soderstrom.train.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/soderstrom.train.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/soderstrom.train.all.lst
      thomas:
        train:
          annotated: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/thomas.train.all.uem
          annotation: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/thomas.train.all.rttm
          uri: /scratch2/sdas/DATA/train-superdataset/VTC_files_4-0/thomas.train.all.lst
  BBT2:
    SpeakerDiarization:
      vanuatu:
        test:
          annotated: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/test/vanuatu.test.uem
          annotation: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/test/vanuatu.test.rttm
          uri: /scratch2/mmetais/vtc2.0/BBT2_lst/test/vanuatu.test.lst
      tsimane:
        test:
          annotated: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/test/tsimane.test.uem
          annotation: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/test/tsimane.test.rttm
          uri: /scratch2/mmetais/vtc2.0/BBT2_lst/test/tsimane.test.lst
      tsay:
        test:
          annotated: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/test/tsay.test.uem
          annotation: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/test/tsay.test.rttm
          uri: /scratch2/mmetais/vtc2.0/BBT2_lst/test/tsay.test.lst
      namibia:
        test:
          annotated: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/test/namibia.test.uem
          annotation: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/test/namibia.test.rttm
          uri: /scratch2/mmetais/vtc2.0/BBT2_lst/test/namibia.test.lst
      lena:
        test:
          annotated: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/test/lena.test.uem
          annotation: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/test/lena.test.rttm
          uri: /scratch2/mmetais/vtc2.0/BBT2_lst/test/lena.test.lst
      aclew:
        test:
          annotated: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/test/aclew.test.uem
          annotation: /scratch2/mlavechin/VoiceTypeClassifierPaper/DATA/BabyTrain_full_resplitted2/test/aclew.test.rttm
          uri: /scratch2/mmetais/vtc2.0/BBT2_lst/test/aclew.test.lst
  X:
    SpeakerDiarization:   
      DATASET:
        train:
          DATASET.SpeakerDiarization.cougar:
          - train
          DATASET.SpeakerDiarization.vanuatu:
          - train
          DATASET.SpeakerDiarization.tsimane2017:
          - train
          DATASET.SpeakerDiarization.png2019:
          - train
          DATASET.SpeakerDiarization.lyon:
          - train
          DATASET.SpeakerDiarization.fausey-trio:
          - train
          DATASET.SpeakerDiarization.providence:
          - train
          DATASET.SpeakerDiarization.soderstrom:
          - train
          DATASET.SpeakerDiarization.tsay:
          - train
          DATASET.SpeakerDiarization.thomas:
          - train
        development:
          DATASET.SpeakerDiarization.cougar:
          - development
          DATASET.SpeakerDiarization.vanuatu:
          - development
          DATASET.SpeakerDiarization.tsimane2017:
          - development
          DATASET.SpeakerDiarization.lyon:
          - development
          DATASET.SpeakerDiarization.fausey-trio:
          - development
          DATASET.SpeakerDiarization.providence:
          - development
          DATASET.SpeakerDiarization.tsay:
          - development
      BBT2:
        test:
          BBT2.SpeakerDiarization.vanuatu:
          - test
          BBT2.SpeakerDiarization.tsimane:
          - test
          BBT2.SpeakerDiarization.tsay:
          - test
          BBT2.SpeakerDiarization.namibia:
          - test
          BBT2.SpeakerDiarization.lena:
          - test
          BBT2.SpeakerDiarization.aclew:
          - test

